[package]
name = "biotoxin495/uihighlighter"
description = "A lightweight client-side utility for highlighting GuiObjects with animated arrows."
version = "1.0.3"
license = "MIT"
authors = ["biotoxin495"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/biotoxin495/UIHighlighter"

exclude = [
	"examples",
	"docs",
	".github",
	"*.rbxl",
	"*.rbxlx",
]